### ISSUE TITLE
Unable to Train Model - Error: "ValueError: No gradients provided for any variable"

### ISSUE THREAD

**Issue by YK-2002** [nicenustian/stock-market-predictions-with-bayesian-lstm#1]
### Steps to Reproduce
1. Attempted to train the model using code from train.py.
2. Loaded the dataset into the model.
3. Called the train function with specified parameters for training.

### Expected Behavior
Expected the model to train successfully and output training results.

### Actual Behavior
Encountered an error while executing the training, throwing "ValueError: No gradients provided for any variable." Unable to resolve the issue.

### Environment Information
- Operating System: Windows 10
- Python Version: 3.8.5
- TensorFlow Version: 2.7.0

### Screenshots
![image](https://github.com/nicenustian/stock-market-predictions-with-bayesian-lstm/assets/68959228/d5da1692-810d-4e65-934b-e2b1ca4b0a29)

[Screenshot Link](link)

### Attempts to Resolve
- Reviewed model structure and input data, found no apparent issues.
- Attempted to reinstall TensorFlow and related libraries, but the problem persists.

Appreciate any assistance or guidance to resolve this issue!

**Comment by nicenustian** [comment]
The reason is there is no dataset downloaded, as the down flag is False by default. The code downloads data from yahoo finance in a created folder.  I have set the flag to True by default.

**Comment by nicenustian** [comment]
Now the download flag set to True by default this should be the output.

tickers =  ['AAPL', 'MSFT', 'AMZN', 'GOOGL']
dates (start, end, validation) 2019-01-22 19:48:43.128497 2024-01-21 19:48:43.128497 2023-01-21
epochs, lr, batch_size layers =  1000 1e-04 32 4
time steps (input, output) =  120 30
Directory 'tech_stocks_combined/date2019-01-22_inout12030/' already exists.
[*********************100%%**********************]  1 of 1 completed
tech_stocks_combined/date2019-01-22_inout12030/AAPL.csv
[*********************100%%**********************]  1 of 1 completed
tech_stocks_combined/date2019-01-22_inout12030/MSFT.csv
[*********************100%%**********************]  1 of 1 completed
tech_stocks_combined/date2019-01-22_inout12030/AMZN.csv
[*********************100%%**********************]  1 of 1 completed
tech_stocks_combined/date2019-01-22_inout12030/GOOGL.csv


Train all stocks as one combined model but training in sequentially..

===========================================
tech_stocks_combined/date2019-01-22_inout12030/AAPL.csv
train dataset <bound method DataFrame.info of             Date        Open        High  ...       Close   Adj Close     Volume
0     2019-01-23   38.537498   38.785000  ...   38.480000   36.933525   92522400
1     2019-01-24   38.527500   38.619999  ...   38.174999   36.640778  101766000
2     2019-01-25   38.869999   39.532501  ...   39.439999   37.854939  134142000
3     2019-01-28   38.947498   39.082500  ...   39.075001   37.504612  104768400
4     2019-01-29   39.062500   39.532501  ...   38.669998   37.115891  166348800
         ...         ...         ...  ...         ...         ...        ...
1002  2023-01-13  132.029999  134.919998  ...  134.759995  134.010941   57809700
1003  2023-01-17  134.830002  137.289993  ...  135.940002  135.184387   63646600
1004  2023-01-18  136.820007  138.610001  ...  135.210007  134.458450   69672800
1005  2023-01-19  134.080002  136.250000  ...  135.270004  134.518112   58280400
1006  2023-01-20  135.279999  138.020004  ...  137.869995  137.103653   80223600

[1007 rows x 7 columns]>
test dataset <bound method DataFrame.info of             Date        Open        High  ...       Close   Adj Close    Volume
1007  2023-01-23  138.119995  143.320007  ...  141.110001  140.325653  81760300
1008  2023-01-24  140.309998  143.160004  ...  142.529999  141.737762  66435100
1009  2023-01-25  140.889999  142.429993  ...  141.860001  141.071472  65799300
1010  2023-01-26  143.169998  144.250000  ...  143.960007  143.159821  54105100
1011  2023-01-27  143.160004  147.229996  ...  145.929993  145.118851  70555800
         ...         ...         ...  ...         ...         ...       ...
1252  2024-01-12  186.059998  186.740005  ...  185.919998  185.919998  40444700
1253  2024-01-16  182.160004  184.259995  ...  183.630005  183.630005  65603000
1254  2024-01-17  181.270004  182.929993  ...  182.679993  182.679993  47317400
1255  2024-01-18  186.089996  189.139999  ...  188.630005  188.630005  78005800
1256  2024-01-19  189.330002  191.949997  ...  191.559998  191.559998  68741000

[250 rows x 7 columns]>
train/val samples  (1107, 120, 5) (1107, 30) (100, 120, 5) (100, 30)
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 120, 5)]          0         
                                                                 
 LSTMLayer1 (Bidirectional)  (None, 120, 60)           8640      
                                                                 
 LSTMLayer2 (Dropout)        (None, 120, 60)           0         
                                                                 
 LSTMLayer3 (Bidirectional)  (None, 120, 60)           21840     
                                                                 
 LSTMLayer4 (Dropout)        (None, 120, 60)           0         
                                                                 
 LSTMLayer5 (Bidirectional)  (None, 120, 60)           21840     
                                                                 
 LSTMLayer6 (Dropout)        (None, 120, 60)           0         
                                                                 
 LSTMLayer7 (Bidirectional)  (None, 60)                21840     
                                                                 
 LSTMLayer8 (Dropout)        (None, 60)                0         
                                                                 
 dense (Dense)               (None, 60)                3660      
                                                                 
 dist (DistributionLambda)   ((None, 30),              0         
                              (None, 30))                        
                                                                 
=================================================================
Total params: 77,820
Trainable params: 77,820
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000..
